#!/bin/bash
# Generate .Renviron from the pixi environment prefix.
#
# Purpose: RStudio Server spawns rsession outside pixi activation. A
# project-level .Renviron lets rsession discover pixi-managed R packages
# without pixi needing to launch it. .Renviron is read by R at session startup.
#
# Note: activation.scripts run before activation.env is applied, so variables
# like R_LIBS are not yet available. CONDA_PREFIX is reliably set by pixi
# before scripts execute.

set -eu

: "${CONDA_PREFIX:?CONDA_PREFIX is not set — this script must run inside pixi activation}"

R_PREFIX="${CONDA_PREFIX}/lib/R"

cat > "${PIXI_PROJECT_ROOT:-.}/.Renviron" <<EOF
# Auto-generated by pixi activation (scripts/generate-renviron.sh).
# DO NOT EDIT — this file is regenerated on every pixi activation.
#
# R_HOME is intentionally omitted: RStudio Server sets it before .Renviron
# is read, and overriding it crashes the rsession.

R_LIBS=${R_PREFIX}/library
R_LIBS_USER=${R_PREFIX}/library
PATH=${CONDA_PREFIX}/bin:${PATH}
LD_LIBRARY_PATH=${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH:-}
EOF
